### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by raulseixasbr** [Koolkev246/gsmst-LetsSurf#1]
When i build it on unity, there's a script saying fragsurf was not found. When I fix that, the console display no more errors but there are a lot of gameobjects with missing scripts.

**Comment by Kevin-Kwan** [comment]
Yep, you're right, sorry about that. Something must've went wrong when I was pushing files, and I didn't double check that all the files were correct and in place. I'm am currently not at the computer where my main files are. I will be back at my computer in about a week. I will try to fix the issue then.

**Comment by Kevin-Kwan** [comment]
@raulseixasbr I have fixed the branch. Let me if there are any more issues. Thank you again for bringing this issue to my attention!

**Comment by raulseixasbr** [comment]
Thank you!
